### ISSUE TITLE
Chained Builder-Classes with one setter each for compile-time checking

### ISSUE THREAD

**Issue by fab1an** [google/FreeBuilder#107]
Would it be feasible to generated a partial Builder class for each field, with each Builder having one setter that returns the next Builder, so I can ensure on compile-time that all fields have been set? Also they would be always set in the same order in the code.

**Comment by cjp39** [comment]
Unfortunately the annotation processor can't reliably tell what fields have defaults set (the code in the constructor is opaque without an ugly javac-specific hack that may not work in future versions).

What I would like to do is use said javac-specific hack to check all fields have been set at compile-time; if it fails, or if your code is more complex than "set all fields in order", you only lose that check, rather than having invalid code generated.

Thanks for the suggestion!
Chris
