### ISSUE TITLE
`Unsupported major.minor version 51.0` usgin this lib with jdk 6

### ISSUE THREAD

**Issue by gerferra** [google/FreeBuilder#120]
I get:

java.lang.UnsupportedClassVersionError: org/inferred/freebuilder/shaded/com/google/googlejavaformat/java/FormatterException : Unsupported major.minor version 51.0

when compiling with jdk 1.6.

The readme says "Automatic generation of the Builder pattern for Java 1.6+". 

Can I use the lib with jdk 1.6 or I must use jdk 1.7 and generate 1.6 bytecode?

**Comment by chrisalice** [comment]
Hi Germán,

Thanks for flagging this issue! FreeBuilder is intended to be usable with OpenJDK 6, but because of resource constraints, we actually only test with a single JDK release. Looks like #88 is the culprit here. I'll look into fixing this issue; as a workaround, you can either compile with a JDK 7, or use
[FreeBuilder v1.3.1](https://github.com/google/FreeBuilder/releases/tag/v1.3.1) ([ docs here](https://github.com/google/FreeBuilder/blob/v1.3.1/README.)) If you don't need any of the more recent features.

Sorry for the inconvenience!
Chris

**Comment by gerferra** [comment]
Ok. Thank you :+1:

**Comment by chrisalice** [comment]
This is now fixed in [v1.7.2](https://github.com/google/FreeBuilder/releases/tag/v1.7.2). Unfortunately due to resource constraints, and because Java 6 is EOL, we've gone with disabling the (Java 7+) formatter in JDK 6, so the output code will be less readable than it was in v1.3.1. I hope that doesn't cause serious issues?

**Comment by gerferra** [comment]
I think is a fair tradeoff. Thanks.
