### ISSUE TITLE
Nested @FreeBuilder Bar in a separate file doesn't generate get getBarBuilder

### ISSUE THREAD

**Issue by aabdagic** [google/FreeBuilder#28]
For
```java
@FreeBuilder
public interface Foo {
  Bar getBar();
  static class Builder extends Foo_Builder() {}
  @FreeBuilder
  public interface Bar {
   String getBlah();
   static class Builder extends Foo_Bar_Builder() {}
  }
}
```
this works fine:
```java new Foo.Builder().getBarBuilder()```

But for:
```java
@FreeBuilder
public interface Foo {
  Bar getBar();
  static class Builder extends Foo_Builder() { }
}
```
```java
@FreeBuilder
public interface Bar {
 String getBlah();
 static class Builder extends Bar_Builder() {}
}
```
```java new Foo.Builder().getBarBuilder()``` doesn't exist.

**Comment by cjp39** [comment]
Appears to occur only in Eclipse.

**Comment by cjp39** [comment]
Specifically, to reproduce, you need Eclipse to be running its incremental compiler (e.g. by touching the Foo file above). A clean build in a standard (non-Google) Eclipse configuration will not trigger the error.

It turns out Eclipse's incremental compiler only discovers RetentionLevel.CLASS annotations on other classes, while @FreeBuilder was marked RetentionLevel.SOURCE (because that's all that's strictly required). As a workaround until #11 is fixed, we can use RetentionLevel.CLASS.

**Comment by cjp39** [comment]
Reopening this. Eclipse is validly giving us only JAR-level information, albeit in a surprising situation. The actual bug is that we only check the methods declared on the user's Builder type to determine whether it provides the methods we need (clear, etc.), while @FreeBuilder methods are, of course, declared on the superclass.

**Comment by cjp39** [comment]
Reverted workaround because:
  * otherwise our claim that "you can always walk away with the code @FreeBuilder generated" is no longer true
  * it's a hassle to change the @FreeBuilder annotation in the Google codebase, and I'm lazy
